name: Deploy API to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - .github/workflows/gh-pages-api.yml
      - devices/*.json
      - profiles/*.json

concurrency: gh-pages-deployment
jobs:
  deploy:
    name: Deploy API to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Generate static API
        run: |
          python generate_static_api.py

      - name: Deploy API to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: site/api/
          target-folder: api/
          force: false
